# Generated by Django 5.0.3 on 2024-03-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='size',
            field=models.IntegerField(default=1),
        ),
    ]
